"""add bond names, update maturities

Revision ID: d065ad18d7ed
Revises: 758073aa4291
Create Date: 2026-04-24 13:24:49.374978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd065ad18d7ed'
down_revision: Union[str, Sequence[str], None] = '758073aa4291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bond_maturities', sa.Column('bond_name', sa.String(), nullable=False))
    op.alter_column('bond_maturities', 'principal_received',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.create_unique_constraint(None, 'bond_maturities', ['bond_figi'])
    op.drop_column('bond_maturities', 'operation_id')
    op.add_column('bond_purchases', sa.Column('bond_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bond_purchases', 'bond_name')
    op.add_column('bond_maturities', sa.Column('operation_id', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'bond_maturities', type_='unique')
    op.alter_column('bond_maturities', 'principal_received',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.drop_column('bond_maturities', 'bond_name')
    # ### end Alembic commands ###
